-- Generated by: https://github.com/ArnaudValensi/xdg-menu-to-awesome-wm.git
-- Icons added manually
local beautiful = require("beautiful") -- Theme handling library

submenu0 = {
  { "Archive Manager", "file-roller" },
  { "Calculator", "gnome-calculator" },
  { "Character Map", "gucharmap" },
  { "Clocks", "gnome-clocks" },
  { "Contacts", "gnome-contacts" },
  { "Disks", "gnome-disks" },
  { "Documents", "gnome-documents" },
  { "Files", "nautilus --new-window" },
  { "Font Viewer", "gnome-font-viewer" },
  { "gedit", "gedit" },
  { "gtk-chtheme", "gtk-chtheme" },
  { "Help", "yelp" },
  { "Orca", "orca --replace" },
  { "Passwords and Keys", "/usr/bin/seahorse" },
  { "Screenshot", "gnome-screenshot --interactive" },
  { "Tweak Tool", "gnome-tweak-tool" },
  { "Vi IMproved", "gvim -f" }
}
submenu1 = {
  { "Document Viewer", "evince" },
  { "GNU Image Manipulation Program", "gimp-2.8" },
  { "LibreOffice Draw", "libreoffice --draw" },
  { "Shotwell", "shotwell" },
  { "Simple Scan", "simple-scan" }
}
submenu2 = {
  { "Dropbox", "dropbox start -i" },
  { "Empathy", "empathy" },
  { "Firefox", "firefox" },
  { "Google Chrome", "/opt/google/chrome/google-chrome" },
  { "Pidgin Internet Messenger", "pidgin" },
  { "Remote Desktop Viewer", "vinagre" },
  { "Thunderbird", "thunderbird" },
  { "Transmission", "transmission-gtk" },
  { "XChat", "xchat" }
}
submenu3 = {
  { "Dictionary", "gnome-dictionary" },
  { "Document Viewer", "evince" },
  { "Evolution", "evolution" },
  { "LibreOffice Calc", "libreoffice --calc" },
  { "LibreOffice Draw", "libreoffice --draw" },
  { "LibreOffice Impress", "libreoffice --impress" },
  { "LibreOffice Writer", "libreoffice --writer" }
}
submenu4 = {
  { "Weather", "gnome-weather" }
}
submenu5 = {
  { "gitg", "gitg" },
  { "Git GUI", "git gui" },
  { "Qt4 QDbusViewer", "qdbusviewer" }
}
submenu6 = {
  { "Cheese", "cheese" },
  { "EasyTAG", "easytag" },
  { "GNOME MPlayer", "gnome-mplayer" },
  { "Rhythmbox", "rhythmbox" },
  { "Videos", "totem" }
}
myappmenu = {
  { "Accessories",   submenu0, beautiful.icon_path .. "categories/applications-accessories.svg" },
  { "Graphics",      submenu1, beautiful.icon_path .. "categories/applications-graphics.svg" },
  { "Internet",      submenu2, beautiful.icon_path .. "categories/applications-internet.svg" },
  { "Office",        submenu3, beautiful.icon_path .. "categories/applications-office.svg" },
  { "Other",         submenu4, beautiful.icon_path .. "categories/applications-other.svg" },
  { "Programming",   submenu5, beautiful.icon_path .. "categories/applications-development.svg" },
  { "Sound & Video", submenu6, beautiful.icon_path .. "categories/applications-multimedia.svg" },
  { "System Tools",  submenu7, beautiful.icon_path .. "categories/applications-system.svg" }
}
